### ISSUE TITLE
WiFi module upgrade?

### ISSUE THREAD

**Issue by lynxthecat** [kamaradclimber/miele-network#4]
Dear @kamaradclimber,

Nice work with this. I stumbled upon your project because as an OpenWrt user myself I’ve also been trying to figure out something relating to my Miele coffee machine and oven. Maybe you have an idea. 

Have you ever upgraded the WiFi module on your washing machine? You might see that option if you open the Miele smart home app for controlling Miele devices. 

My Miele coffee machine and oven come up on the Miele smart home app as requiring a WiFi module upgrade. But when I start said upgrade on the app, the upgrade never seems to work. I can’t figure out why. 

The coffee machine, oven and iPad running the Miele app are all connected on my OpenWrt 2.4 GHz guest network and normally devices can communicate with each other on that network.

**Comment by kamaradclimber** [comment]
Hello, I've paused work on my miele washing machine for now.
Thanks for your kind words though!

I don't remember anything related to wifi module, for now I've tried to avoid using the app as much as possible.

**Comment by lynxthecat** [comment]
Thanks for your reply. My thinking is that if Miele wants to push a WiFi module update it is presumably security related? Well actually I am probably just more frustrated that it is not working and trying to see if I can get it to work.

**Comment by lynxthecat** [comment]
@kamaradclimber I have another question - do you see lots of 'tx retries' and 'tx fails' associated with your washing machine if you issue an 'iw dev' 'station dump' from your OpenWrt router? From an AP to which my Miele device is (connected to main router via WDS), I see:

https://pastebin.com/uvhHJmXf
